site_name: MkDocs SVG to PNG Plugin
site_url: https://nuitsjp.github.io/mkdocs-svg-to-png/
repo_url: https://github.com/nuitsjp/mkdocs-svg-to-png

theme:
  name: material
  language: ja

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: svg
          class: svg
  - pymdownx.highlight
  - toc:
      permalink: true

plugins:
  - search
  - svg-to-png:
      enabled_if_env: ENABLE_PDF_EXPORT
      output_format: png
      dpi: 300
      quality: 95
      background_color: "transparent"
      cache_enabled: true
      cache_dir: ".svg_cache"
      preserve_original: false
      error_on_fail: false
      log_level: "INFO"
      cleanup_generated_images: false
      temp_dir: null
  - to-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      cover_subtitle: 'MkDocs SVG to PNG'
      toc_title: 目次
      toc_level: 3
      output_path: MkDocs-SVG-to-PNG.pdf
